import type { Metadata } from "next";
import "./globals.css";
import { QueryProvider } from "@/providers";
import { Toaster } from "@/components/ui/sonner";
import { Nunito_Sans } from "next/font/google";


const nunitoSans = Nunito_Sans({
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunitoSans.className}`}
      >
      <QueryProvider>
        {children}
      </QueryProvider>
      <Toaster/>
      </body>
    </html>
  );
}
